FROM ubuntu:latest                                                                                                                                                                                                                                                            
RUN apt update && apt install  openssh-server sudo -y                                                                                                                                                                                                                         
RUN apt-get install boxes --fix-missing -y
RUN apt-get install figlet -y

RUN unset HISTFILE
RUN useradd -rm -d /home/challenge1 -s /bin/bash -u 1000 challenge1 
RUN echo "figlet -f standard "Challenge 1"| boxes -d scroll; echo "                    Let's try type cat readme.md"" >> home/challenge1/.bashrc

RUN chown -R root:root /home/challenge1 
COPY flag.txt /home/challenge1/flag.txt
COPY readme.md /home/challenge1/readme.md
RUN chmod 704 /home/challenge1
RUN echo 'challenge1:ehcgreat' | chpasswd
RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
